version: '2'
services:
  ufp-swagger-proxy:
    image: ufp-swagger-proxy-app:6
    environment:
    - URL=http://swagger-petstore:8080/api/swagger.json
    ports:
    - "3000:8080"
  ufp-swagger-proxy-yaml:
    image: ufp-swagger-proxy-app:6
    environment:
    - URL=http://wiremock-petstore:8080/v2/swagger.yaml
    ports:
    - "3001:8080"
